apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio # Debe coincidir con el label 'app' de tu Deployment
  ports:
    - protocol: TCP
      port: 80 # Puerto del servicio (al que se conectarán los usuarios)
      targetPort: 80 # Puerto del contenedor al que se redirige el tráfico
  type: NodePort # Permite acceder al servicio desde fuera del clúster (útil para Minikube)